name = "gis-umkm-rengging"
compatibility_date = "2024-12-01"
pages_build_output_dir = ".vercel/output/static"

[build]
command = "npx @cloudflare/next-on-pages"

[build.environment]
NODE_VERSION = "22"
